# Generated by Django 5.1.1 on 2024-10-22 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
