# Generated by Django 5.1.1 on 2024-10-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_created_by_alter_property_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='created_by',
            new_name='author',
        ),
    ]
