# Generated by Django 5.1.1 on 2024-10-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_rename_created_by_property_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('NGN', 'Naira')], default='USD', max_length=3),
        ),
    ]
